// StrideAndRun Runners Database
const runnersData = [
    { 
        name: "Clayton", 
        attendance: 9, 
        friendsBrought: 8, 
        runHistory: "R1, R2, R3", 
        role: "Founder", 
        contact: "clayton_@runnerclub.io", 
        founderStatus: "✅", 
        pace: "4:45", 
        streak: 28, 
        notes: "Race organizer" 
    },
    { 
        name: "Jack", 
        attendance: 7, 
        friendsBrought: 5, 
        runHistory: "R2, R3", 
        role: "Social and Inner Harbor Admin", 
        contact: "jack@runnershq.com", 
        founderStatus: "✅", 
        pace: "5:20", 
        streak: 14, 
        notes: "Social media coordinator" 
    },
    { 
        name: "Bess", 
        attendance: 3, 
        friendsBrought: 1, 
        runHistory: "R1, R2, R3", 
        role: "Lake Trainer Party, creator", 
        contact: "bess.runner@gmail.com", 
        founderStatus: "✅", 
        pace: "5:15", 
        streak: 6, 
        notes: "Trail specialist" 
    },
    { 
        name: "Esperanza", 
        attendance: 5, 
        friendsBrought: 3, 
        runHistory: "R1, R2, R3", 
        role: "Lake Trainer Party, founder", 
        contact: "esperanza@runclub.org", 
        founderStatus: "✅", 
        pace: "4:55", 
        streak: 21, 
        notes: "Marathon coach" 
    },
    { 
        name: "Kaleel", 
        attendance: 3, 
        friendsBrought: 2, 
        runHistory: "R1, R2", 
        role: "Social Media", 
        contact: "kaleel.media@gmail.com", 
        founderStatus: "✅", 
        pace: "5:05", 
        streak: 12, 
        notes: "Photography lead" 
    },
    { 
        name: "Damien", 
        attendance: 2, 
        friendsBrought: 3, 
        runHistory: "R1, R3", 
        role: "", 
        contact: "damien82@hotmail.com", 
        founderStatus: "pending", 
        pace: "5:30", 
        streak: 4, 
        notes: "New member coordinator" 
    },
    { 
        name: "Corey", 
        attendance: 1, 
        friendsBrought: 2, 
        runHistory: "R1", 
        role: "Run ATX Instagram", 
        contact: "@triangulate", 
        founderStatus: "pending", 
        pace: "4:40", 
        streak: 0, 
        notes: "Social media specialist" 
    },
    { 
        name: "Celine", 
        attendance: 4, 
        friendsBrought: 2, 
        runHistory: "R2", 
        role: "DJ Set", 
        contact: "celine.beats@gmail.com", 
        founderStatus: "pending", 
        pace: "5:25", 
        streak: 7, 
        notes: "Event DJ" 
    },
    { 
        name: "Dimitri L.", 
        attendance: 2, 
        friendsBrought: 1, 
        runHistory: "R1, R2", 
        role: "Pacer", 
        contact: "dimitri@pacinglead.com", 
        founderStatus: "pending", 
        pace: "4:30", 
        streak: 5, 
        notes: "5K specialist" 
    },
    { 
        name: "Kassandra S.", 
        attendance: 1, 
        friendsBrought: 2, 
        runHistory: "R2", 
        role: "DJ Set", 
        contact: "kass.sounds@mixcloud.com", 
        founderStatus: "pending", 
        pace: "5:10",
